language: ruby

services:
  - redis-server

rvm:
  - 2.3.4

gemfile:
  - Gemfile
  - gemfiles/Gemfile.activesupport-4.2.x

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter

notifications:
  email: false
